### PR TITLE
fix: prevent `SyntaxError` while parsing `:has` pseudo selectors

### PR DESCRIPTION
**Pull request by seckardt**
Fix for issue #111

### CODE REVIEW

**Comment by dperini** [comment]
@seckardt 
Yes ... there are other similar issues that were introduced between 2.2.x and 2.2.7 because of poor testing on my side.
I am finally home ready to land several patches and improvements so I need help from everybody using "nwsapi".

I have to complete setting up a continuous testing tool, based on WPT which has been delayed for several months now.
This will be something useful for everybody and would be used to confirm bugs after comparing functionality and outcome with standards browser behaviours.

Thank you so much for your great contribution.
Looking forward for other fixes, stay tuned.
Your help much appreciated.

**Comment by seckardt** [comment]
@dperini Any ETA when either this PR or another/wider fix might hit `master` and leads to a new release?

**Comment by dperini** [comment]
@seckardt 
it will be very soon. I hope to have master updated & ready to test then push to npm 2.2.10.
I am executing all my tests and wpt tests once more to ensure not forgetting obvious checks.

**Comment by dperini** [comment]
@seckardt 
I merged your fix ... can you check it out for last minute bugs that you might have encountered ?
Thank you.

**Pull request merged**
